export const GATE_BRANCHES = [
  { code: 'AE', name: 'Aerospace Engineering' },
  { code: 'AG', name: 'Agricultural Engineering' },
  { code: 'AR', name: 'Architecture and Planning' },
  { code: 'BM', name: 'Biomedical Engineering' },
  { code: 'BT', name: 'Biotechnology' },
  { code: 'CE', name: 'Civil Engineering' },
  { code: 'CH', name: 'Chemical Engineering' },
  { code: 'CS', name: 'Computer Science & IT' },
  { code: 'CY', name: 'Chemistry' },
  { code: 'DA', name: 'Data Science & AI' },
  { code: 'EC', name: 'Electronics & Communication' },
  { code: 'EE', name: 'Electrical Engineering' },
  { code: 'ES', name: 'Environmental Science' },
  { code: 'EY', name: 'Ecology and Evolution' },
  { code: 'GE', name: 'Geomatics Engineering' },
  { code: 'GG', name: 'Geology and Geophysics' },
  { code: 'IN', name: 'Instrumentation Engineering' },
  { code: 'MA', name: 'Mathematics' },
  { code: 'ME', name: 'Mechanical Engineering' },
  { code: 'MN', name: 'Mining Engineering' },
  { code: 'MT', name: 'Metallurgical Engineering' },
  { code: 'NM', name: 'Naval Architecture & Marine' },
  { code: 'PE', name: 'Petroleum Engineering' },
  { code: 'PH', name: 'Physics' },
  { code: 'PI', name: 'Production & Industrial' },
  { code: 'ST', name: 'Statistics' },
  { code: 'TF', name: 'Textile Engineering & Fibre' },
  { code: 'XE', name: 'Engineering Sciences' },
  { code: 'XH', name: 'Humanities & Social Sciences' },
  { code: 'XL', name: 'Life Sciences' }
];
